#!/usr/bin/env python3
"""
MoHoLocal — Seed 150 additional businesses: Lathrop + Manteca + Brentwood
Focus: Home Services, Restaurants, Health & Wellness, Education, Family Services
Run from Mac terminal: python3 ~/Desktop/MoHoLocal/seed_businesses_6.py
"""

import json
import urllib.request
import urllib.error

SUPABASE_URL = "https://ozjlfgipfzykzrjakwzb.supabase.co"
SERVICE_ROLE_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
    ".eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96amxmZ2lwZnp5a3pyamFrd3piIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjQzMzI3NiwiZXhwIjoyMDg4MDA5Mjc2fQ"
    ".g9f2Il1nWEfgyuvTXHUiHn4EgWsrHVV1QBbdxehT0gM"
)

BUSINESSES = [

    # ═══════════════════════════════════════════════════════════════════════
    # LATHROP  (50)
    # ═══════════════════════════════════════════════════════════════════════

    # — Home Services (12) —
    {
        "name": "River Islands Roofing",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Residential roofing installation and repair for Lathrop and River Islands homes. Tile, shingle, and cool-roof specialists. Free estimates.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9001",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop HVAC & Plumbing",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Combined heating, cooling, and plumbing services for Lathrop homes. Emergency calls answered 24/7 with no overtime charge.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9002",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manthey Rd Landscaping",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Full lawn care, landscape design, and irrigation installation for Lathrop properties. Drought-tolerant planting and seasonal clean-ups.",
        "address": "Manthey Rd, Lathrop, CA 95330",
        "phone": "(209) 858-9003",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Solar Pros",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Residential solar panel and battery storage installation in Lathrop. Local installers, competitive financing, and 25-year production guarantee.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9004",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Harlan Electric Co.",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Licensed electricians in Lathrop for panel upgrades, EV charger installation, smart home wiring, and outdoor lighting. Free estimates.",
        "address": "S Harlan Rd, Lathrop, CA 95330",
        "phone": "(209) 858-9005",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Pool & Spa Care",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Weekly pool cleaning, chemical service, and equipment repair for Lathrop and River Islands homes. New pool construction available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9006",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Painting Co.",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Interior and exterior residential painting for Lathrop and River Islands communities. Premium paints, clean crews, on-time completion.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9007",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Garage Door & Gates",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Garage door repair, spring replacement, and smart opener upgrades for Lathrop residents. Driveway gate installation and automation.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9008",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Clean Slate Housekeeping Lathrop",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Residential cleaning service for Lathrop homes. Weekly, bi-weekly, and one-time deep cleans using eco-certified products. Bonded and insured.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9009",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Louise Ave Tile & Stone",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Tile installation, natural stone work, and bathroom remodeling for Lathrop homeowners. Kitchen backsplashes, showers, and flooring.",
        "address": "Louise Ave, Lathrop, CA 95330",
        "phone": "(209) 858-9010",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Pest Solutions",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Family-safe pest control for Lathrop homes. Ants, spiders, rodents, termites, and gophers. Monthly plans and one-time treatments available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9011",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Roth Rd Remodeling",
        "category": "Home Services",
        "city": "Lathrop",
        "description": "Full kitchen and bathroom remodeling contractor serving Lathrop. Design-build service with licensed general contractors and 3D visualization.",
        "address": "Roth Rd, Lathrop, CA 95330",
        "phone": "(209) 858-9012",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Restaurants (12) —
    {
        "name": "Lathrop Grill & Bar",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "American grill in Lathrop serving steaks, ribs, burgers, and craft beers on tap. Sports bar atmosphere with daily happy hour specials.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9013",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Taqueria Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Authentic street tacos, burritos, and quesadillas made fresh daily in Lathrop. Homemade salsas and tortillas. Quick service for lunch crowds.",
        "address": "S Harlan Rd, Lathrop, CA 95330",
        "phone": "(209) 858-9014",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Café",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Neighborhood café in Lathrop's River Islands community. Espresso drinks, bagels, avocado toast, and grab-and-go lunches. Opens at 6 AM.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9015",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Saffron Indian Kitchen Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "North and South Indian cuisine in Lathrop. Butter chicken, dosas, biryani, and fresh naan. Lunch buffet available weekdays.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9016",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pho Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Vietnamese pho, vermicelli bowls, and fresh spring rolls in Lathrop. Generous portions, house-made broth, and quick weekday lunch service.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9017",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pizza Primo Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "New York-style pizza by the slice or whole pie in Lathrop. Calzones, pasta, and garlic knots. Family dinner specials Tuesday through Thursday.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9018",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lotus Garden Chinese Restaurant",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Traditional Chinese cuisine in Lathrop with dim sum on weekends, seafood dishes, and family-style dinner plates. Banquet room available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9019",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Sandwich Factory Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Gourmet sandwiches, wraps, and grain bowls made fresh to order in Lathrop. Popular with the River Islands lunch crowd. Online ordering available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9020",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Smokehouse BBQ Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Slow-smoked brisket, pulled pork, and ribs in Lathrop. Homemade sides, cornbread, and family platters. Catering for local events.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9021",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunrise Breakfast House Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "All-day breakfast in Lathrop with classic omelets, pancakes, and avocado Benedict. Popular with River Islands families on weekends.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9022",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Falafel & Shawarma Palace",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Middle Eastern street food in Lathrop — shawarma wraps, falafel plates, hummus, and baklava. Halal-certified meats. Open daily for lunch and dinner.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9023",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Burger Basin Lathrop",
        "category": "Restaurants",
        "city": "Lathrop",
        "description": "Smash burgers, loaded fries, and thick milkshakes in Lathrop. Build-your-own options and kids' meal combos. Drive-through window open late.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9024",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },

    # — Health & Wellness (10) —
    {
        "name": "Lathrop Family Health Clinic",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Primary care clinic in Lathrop accepting new patients. Preventive care, chronic disease management, and same-day sick appointments.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9025",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Pediatrics",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Pediatric clinic serving Lathrop and River Islands families. Well-child visits, vaccinations, behavioral health, and telehealth available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9026",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Dental Group",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "General and family dentistry in Lathrop. Cleanings, fillings, crowns, whitening, and pediatric dentistry. Same-day emergency appointments.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9027",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Delta Fit Gym Lathrop",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Full-service gym in Lathrop with free weights, cardio equipment, group classes, and personal training. No long-term contracts required.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9028",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Physical Therapy",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Outpatient physical therapy in Lathrop for sports injuries, back pain, and post-surgical recovery. Most major insurance plans accepted.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9029",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Serenity Counseling Lathrop",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Licensed therapists in Lathrop offering individual and family counseling for anxiety, depression, and relationship challenges. Telehealth available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9030",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Eye Center",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Optometry clinic in Lathrop for comprehensive eye exams, contact lens fittings, and glasses. Pediatric and adult eye care accepted.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9031",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Elevate Yoga Lathrop",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Yoga studio in Lathrop offering vinyasa, restorative, and prenatal yoga classes. Beginner-friendly schedule and monthly membership plans.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9032",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Chiropractic",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Chiropractic adjustments, massage therapy, and sports rehab for Lathrop residents. New patient exams include full spinal assessment.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9033",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Urgent Care",
        "category": "Health & Wellness",
        "city": "Lathrop",
        "description": "Walk-in urgent care clinic in Lathrop for minor injuries, illnesses, lab work, and X-rays. Open 7 days a week with no appointment needed.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9034",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },

    # — Education (6) —
    {
        "name": "Lathrop Learning Center",
        "category": "Education",
        "city": "Lathrop",
        "description": "After-school tutoring for K–12 students in Lathrop. Math, reading, and test prep with credentialed teachers in small-group settings.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9035",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Preschool",
        "category": "Education",
        "city": "Lathrop",
        "description": "Licensed preschool serving River Islands families. Play-based learning, bilingual support, and extended care for working parents.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9036",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Swim Academy",
        "category": "Education",
        "city": "Lathrop",
        "description": "Private and group swim lessons for infants through teens in Lathrop. Drowning prevention, stroke technique, and competitive swim prep.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9037",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Music & Arts Studio",
        "category": "Education",
        "city": "Lathrop",
        "description": "Piano, guitar, and drawing classes for children and adults in Lathrop. Group lessons, private instruction, and annual student recitals.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9038",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Delta Karate Academy",
        "category": "Education",
        "city": "Lathrop",
        "description": "Martial arts classes for children and adults in Lathrop. Karate and jiu-jitsu with character development, anti-bullying, and belt progression.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9039",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop STEM Lab",
        "category": "Education",
        "city": "Lathrop",
        "description": "After-school STEM programs for kids ages 5–14 in Lathrop. Robotics, coding, and science experiments in hands-on weekly sessions.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9040",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Pet Services (5) —
    {
        "name": "Lathrop Pet Hospital",
        "category": "Pet Services",
        "city": "Lathrop",
        "description": "Full-service veterinary hospital in Lathrop for dogs, cats, and small animals. Wellness care, surgery, dental, and emergency services.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9041",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Paws Up Pet Grooming Lathrop",
        "category": "Pet Services",
        "city": "Lathrop",
        "description": "Dog and cat grooming studio in Lathrop. Bath, haircut, nail trim, and spa packages. Breed specialists for doodles, shih tzus, and poodles.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9042",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Dog Walking Co.",
        "category": "Pet Services",
        "city": "Lathrop",
        "description": "Professional dog walking and pet sitting for River Islands and Lathrop residents. Solo walks, group walks, and overnight in-home care.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9043",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Pet Boarding & Daycare",
        "category": "Pet Services",
        "city": "Lathrop",
        "description": "Cage-free dog boarding and daycare in Lathrop. Climate-controlled play areas, daily photo updates, and flexible drop-off/pick-up times.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9044",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop K9 Obedience",
        "category": "Pet Services",
        "city": "Lathrop",
        "description": "Dog obedience training in Lathrop using science-based positive reinforcement. Puppy foundations, basic manners, and off-leash control courses.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9045",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Beauty & Spa (3) —
    {
        "name": "Bliss Nail Spa Lathrop",
        "category": "Beauty & Spa",
        "city": "Lathrop",
        "description": "Nail salon in Lathrop offering gel manicures, dip powder, pedicures, and nail art. Clean tools, relaxing chairs, and friendly staff.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9046",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lathrop Hair Studio",
        "category": "Beauty & Spa",
        "city": "Lathrop",
        "description": "Full-service hair salon in Lathrop for cuts, color, balayage, and blowouts. Walk-ins welcome weekdays. Online booking for weekends.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9047",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Lash & Brow",
        "category": "Beauty & Spa",
        "city": "Lathrop",
        "description": "Lash extensions, brow shaping, and tinting in Lathrop. Classic, hybrid, and volume sets available. Lash refills every 2–3 weeks.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9048",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Automotive (2) —
    {
        "name": "Lathrop Auto Care Center",
        "category": "Automotive",
        "city": "Lathrop",
        "description": "Full-service auto repair in Lathrop. Oil changes, brakes, tires, transmission, and smog checks. Shuttle service available for local customers.",
        "address": "S Harlan Rd, Lathrop, CA 95330",
        "phone": "(209) 858-9049",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "River Islands Car Wash & Detail",
        "category": "Automotive",
        "city": "Lathrop",
        "description": "Full-service car wash and auto detailing in Lathrop. Express wash, hand wax, interior steam cleaning, and ceramic coating available.",
        "address": "Lathrop, CA 95330",
        "phone": "(209) 858-9050",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # MANTECA  (50)
    # ═══════════════════════════════════════════════════════════════════════

    # — Home Services (12) —
    {
        "name": "Manteca Roofing Experts",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Residential roofing repair and full replacements for Manteca homeowners. Tile, shingle, and foam flat roofs. Storm damage specialists.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9001",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Yosemite Ave HVAC",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Heating and cooling service for Manteca homes. AC repair, furnace tune-ups, new system installs, and duct cleaning. Same-day emergency service.",
        "address": "W Yosemite Ave, Manteca, CA 95337",
        "phone": "(209) 823-9002",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Plumbing & Drain",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Drain cleaning, hydro-jetting, water heater replacement, and leak detection for Manteca homes. Licensed, bonded, and available 24/7.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9003",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Green Valley Landscaping Manteca",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Lawn maintenance, garden design, and irrigation systems for Manteca properties. Drought-resistant planting and bi-weekly service routes.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9004",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Solar Solutions",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Residential solar installation and battery backup for Manteca families. Local installers with flexible financing and 25-year warranty.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9005",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Powers Ave Electrical",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Licensed electricians in Manteca for panel upgrades, EV chargers, smart home wiring, and lighting. Free estimates and same-week scheduling.",
        "address": "S Powers Ave, Manteca, CA 95337",
        "phone": "(209) 823-9006",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Painting Pros",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Interior and exterior house painting in Manteca. Detailed prep work, premium paints, and clean finish guaranteed. Free color consultation.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9007",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Daniels St Flooring",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Hardwood, laminate, tile, and carpet installation for Manteca homes. In-home consultations, fast installation, and competitive pricing.",
        "address": "Daniels St, Manteca, CA 95337",
        "phone": "(209) 823-9008",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Fence & Concrete",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Fencing installation and concrete work in Manteca. Driveways, patios, retaining walls, and block walls. Licensed contractor with 10-year guarantee.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9009",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Pool Service Co.",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Weekly pool maintenance, equipment repair, and seasonal opening/closing for Manteca homeowners. Algae treatments and filter replacements.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9010",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Maid Brigade",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Professional house cleaning in Manteca. Standard, deep clean, and move-out services. Eco-friendly products and insured crews.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9011",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Airport Way Remodeling Manteca",
        "category": "Home Services",
        "city": "Manteca",
        "description": "Kitchen, bathroom, and ADU remodeling contractor in Manteca. Full design-build service with 3D renderings and licensed general contractors.",
        "address": "Airport Way, Manteca, CA 95336",
        "phone": "(209) 823-9012",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Restaurants (12) —
    {
        "name": "El Torero Mexican Restaurant",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Family Mexican dining in Manteca with enchiladas, fajitas, and margaritas. Known for weekend brunch and generous portion sizes.",
        "address": "W Yosemite Ave, Manteca, CA 95337",
        "phone": "(209) 823-9013",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Sushi Lounge",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Creative sushi rolls, sashimi, and Japanese small plates in Manteca. Happy hour 4–6 PM weekdays with half-price rolls.",
        "address": "Center St, Manteca, CA 95336",
        "phone": "(209) 823-9014",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Punjab Palace Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Punjabi cuisine in Manteca with tandoori dishes, saag paneer, and fresh lassi. Catering available for weddings and community events.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9015",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Breakfast Club Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "All-day breakfast in Manteca with skillets, French toast, and specialty omelets. Weekend wait is worth it — arrive early for the best seats.",
        "address": "S Main St, Manteca, CA 95337",
        "phone": "(209) 823-9016",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Golden Dragon Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Cantonese and Szechuan favorites in Manteca. Dim sum on weekends, hot pot on Fridays, and takeout available until 10 PM.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9017",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Poke Bowl Bar",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Build-your-own poke bowls with fresh ahi, salmon, and tofu over rice or greens in Manteca. Clean, fast, and customizable. Open for lunch and dinner.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9018",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lela's Soul Kitchen Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Southern comfort food in Manteca — fried chicken, mac and cheese, collard greens, and peach cobbler. Beloved local spot open since 2012.",
        "address": "S Main St, Manteca, CA 95337",
        "phone": "(209) 823-9019",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Taste of Thailand Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Authentic Thai curries, pad thai, spring rolls, and mango sticky rice in Manteca. Spice level adjustable, vegetarian options throughout the menu.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9020",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Brewery & Grill",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Craft beer taproom and American grill in Manteca. 16 rotating taps, burgers, flatbreads, and charcuterie boards. Live music on Saturdays.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9021",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Philly's Cheesesteak Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Authentic Philly cheesesteaks, hoagies, and loaded fries in Manteca. Ribeye shaved daily, Amoroso rolls shipped fresh. Local lunch staple.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9022",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Creekside Coffee Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Specialty coffee, pastries, and light fare in Manteca. Single-origin espresso, matcha, and seasonal drinks. Work-friendly space with free WiFi.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9023",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Super Tacos Manteca",
        "category": "Restaurants",
        "city": "Manteca",
        "description": "Late-night street tacos, burritos, and quesabirria in Manteca. Cash-friendly, quick service, and massive portions. Open until 2 AM on weekends.",
        "address": "E Yosemite Ave, Manteca, CA 95336",
        "phone": "(209) 823-9024",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Health & Wellness (10) —
    {
        "name": "Manteca Family Medicine",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Primary care clinic in Manteca accepting new adult and pediatric patients. Chronic care, physicals, and urgent sick visits with short wait times.",
        "address": "W Yosemite Ave, Manteca, CA 95337",
        "phone": "(209) 823-9025",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Kids Clinic",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Pediatric clinic in Manteca for well-child visits, immunizations, and sick care. Board-certified pediatricians with Spanish-speaking staff.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9026",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Main St Dental Manteca",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Family dental practice in Manteca. Cleanings, Invisalign, implants, crowns, and children's dentistry. Saturday appointments available.",
        "address": "S Main St, Manteca, CA 95337",
        "phone": "(209) 823-9027",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "FitLife Gym Manteca",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "24-hour fitness center in Manteca with free weights, cardio machines, tanning, and personal training. No-contract memberships from $25/month.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9028",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Back & Spine Clinic",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Chiropractic and physical therapy for Manteca residents. Back pain, neck pain, sports injuries, and post-surgical rehab. Same-week new patient slots.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9029",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Horizon Mental Health Manteca",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Therapy and counseling for Manteca residents. Anxiety, depression, trauma, and teen mental health. In-person and telehealth options.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9030",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Clear Vision Eye Care Manteca",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Optometry clinic in Manteca for annual eye exams, contacts, and eyeglasses. Large frame selection and same-day prescription lens orders.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9031",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Acupuncture & Wellness",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Licensed acupuncture clinic in Manteca for pain relief, stress reduction, fertility support, and seasonal health maintenance. New patient specials.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9032",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Bump & Beyond Prenatal Care",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "OB-GYN and midwifery practice in Manteca specializing in prenatal care, labor support, postpartum wellness, and family planning.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9033",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Walk-In Clinic",
        "category": "Health & Wellness",
        "city": "Manteca",
        "description": "Urgent care walk-in clinic in Manteca for non-emergency illness and injury. X-ray, lab work, and STI testing. Open daily 8 AM–8 PM.",
        "address": "Airport Way, Manteca, CA 95336",
        "phone": "(209) 823-9034",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },

    # — Education (6) —
    {
        "name": "Manteca Tutoring & Enrichment",
        "category": "Education",
        "city": "Manteca",
        "description": "K–12 tutoring center in Manteca for math, science, English, and SAT/ACT prep. In-person and online sessions with local credentialed teachers.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9035",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunshine Preschool Manteca",
        "category": "Education",
        "city": "Manteca",
        "description": "Play-based preschool for ages 2–5 in Manteca. Structured curriculum, meals included, and extended care for working families. State licensed.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9036",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Swim School",
        "category": "Education",
        "city": "Manteca",
        "description": "Year-round swim lessons for babies through teens in Manteca. Heated pool, small class sizes, and proven water safety curriculum.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9037",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Dance Studio",
        "category": "Education",
        "city": "Manteca",
        "description": "Ballet, hip-hop, jazz, and contemporary dance for kids through adults in Manteca. Competition team, recitals, and summer intensives available.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9038",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Young Coders Manteca",
        "category": "Education",
        "city": "Manteca",
        "description": "Coding bootcamps for kids 6–16 in Manteca. Web design, game development, Scratch, and Python taught in engaging project-based classes.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9039",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Martial Arts Center",
        "category": "Education",
        "city": "Manteca",
        "description": "Judo, karate, and Brazilian jiu-jitsu for all ages in Manteca. Kids' classes with character development focus and adult competition training.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9040",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Pet Services (5) —
    {
        "name": "Manteca Animal Clinic",
        "category": "Pet Services",
        "city": "Manteca",
        "description": "Veterinary clinic in Manteca providing wellness exams, vaccines, spay/neuter, dental cleanings, and emergency triage for dogs and cats.",
        "address": "W Yosemite Ave, Manteca, CA 95337",
        "phone": "(209) 823-9041",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Mobile Grooming",
        "category": "Pet Services",
        "city": "Manteca",
        "description": "Mobile pet grooming van serving Manteca. Full grooms, bath and brush, de-shed treatments, and nail trims at your front door.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9042",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Furever Home Pet Boarding",
        "category": "Pet Services",
        "city": "Manteca",
        "description": "In-home pet boarding and sitting service in Manteca. Your pet stays in a real home, not a kennel. Daily updates and photo check-ins.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9043",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Big Paws Dog Park & Training",
        "category": "Pet Services",
        "city": "Manteca",
        "description": "Off-leash dog park facility and training classes in Manteca. Socialization sessions, obedience courses, and reactive dog workshops.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9044",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Paws & Whiskers Pet Store Manteca",
        "category": "Pet Services",
        "city": "Manteca",
        "description": "Independent pet store in Manteca with premium food, enrichment toys, supplements, and accessories. Knowledgeable staff for all pet species.",
        "address": "S Main St, Manteca, CA 95337",
        "phone": "(209) 823-9045",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Beauty & Spa (3) —
    {
        "name": "Glow Up Salon Manteca",
        "category": "Beauty & Spa",
        "city": "Manteca",
        "description": "Hair salon in Manteca specializing in cuts, color, extensions, and keratin treatments. Walk-ins welcome Wednesday through Friday.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9046",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Zen Nails & Spa Manteca",
        "category": "Beauty & Spa",
        "city": "Manteca",
        "description": "Nail salon in Manteca with gel manicures, acrylics, pedicures, and paraffin treatments. Clean tools, great staff, and loyalty rewards program.",
        "address": "Manteca, CA 95336",
        "phone": "(209) 823-9047",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Luxe Lash Studio Manteca",
        "category": "Beauty & Spa",
        "city": "Manteca",
        "description": "Lash extensions and brow services in Manteca. Classic, hybrid, and mega volume sets. Refills available every 2–3 weeks with easy online booking.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9048",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Automotive (2) —
    {
        "name": "Manteca Auto & Tire",
        "category": "Automotive",
        "city": "Manteca",
        "description": "Full-service auto repair and tire center in Manteca. Oil changes, alignments, brakes, smog check, and fleet maintenance. Competitive pricing.",
        "address": "Airport Way, Manteca, CA 95336",
        "phone": "(209) 823-9049",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Manteca Detail Kings",
        "category": "Automotive",
        "city": "Manteca",
        "description": "Professional auto detailing in Manteca. Hand wash, clay bar, ceramic coating, paint correction, and interior deep clean. Appointments required.",
        "address": "Manteca, CA 95337",
        "phone": "(209) 823-9050",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # BRENTWOOD  (50)
    # ═══════════════════════════════════════════════════════════════════════

    # — Home Services (12) —
    {
        "name": "Brentwood Roofing & Gutters",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Residential roofing installation, repair, and gutter systems in Brentwood. Licensed contractor serving the Trilogy, Deer Ridge, and Brentwood Hills communities.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9001",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sand Creek HVAC",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Heating and cooling specialists for Brentwood homes. AC repair, furnace service, whole-home air purifiers, and new system installation.",
        "address": "Sand Creek Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9002",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Plumbing Co.",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Licensed plumbers serving Brentwood with water heater installs, repiping, leak detection, and bathroom remodels. 24/7 emergency service.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9003",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lone Tree Landscaping",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Lawn maintenance, landscape design, irrigation, and seasonal clean-ups for Brentwood properties. Drought-tolerant and water-wise specialists.",
        "address": "Lone Tree Way, Brentwood, CA 94513",
        "phone": "(925) 240-9004",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Solar Power",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Residential solar panel and battery backup installation in Brentwood. Local installers with transparent pricing and 25-year production warranty.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9005",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Empire Ave Electric",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Licensed electricians in Brentwood for EV charger installation, panel upgrades, smart home automation, and outdoor lighting.",
        "address": "Empire Ave, Brentwood, CA 94513",
        "phone": "(925) 240-9006",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Pool & Backyard",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Pool cleaning, equipment repair, and backyard landscaping for Brentwood homeowners. Pergola installation and outdoor kitchen builds available.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9007",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Balfour Rd Painting",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Interior and exterior house painting in Brentwood. Premium paints, thorough prep, and clean finish. Free color consultations for new clients.",
        "address": "Balfour Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9008",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Hardwood & Tile",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Hardwood, LVP, and tile installation for Brentwood homes. Kitchen and bathroom tile work, stair refinishing, and in-home consultations.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9009",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Fence & Gates",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Wood, vinyl, and wrought iron fencing for Brentwood properties. Automatic gate installation and driveway automation. Licensed and bonded.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9010",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pristine Home Cleaning Brentwood",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Residential cleaning for Brentwood homes. Weekly, biweekly, and deep-clean services. Eco-friendly products and insured professional crews.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9011",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Remodel & Build",
        "category": "Home Services",
        "city": "Brentwood",
        "description": "Kitchen, bathroom, and ADU remodeling in Brentwood. Licensed general contractor with 3D design service and turnkey project management.",
        "address": "Sellers Ave, Brentwood, CA 94513",
        "phone": "(925) 240-9012",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Restaurants (12) —
    {
        "name": "Casa Brentwood Mexican Kitchen",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Sit-down Mexican restaurant in Brentwood with birria tacos, enchiladas, and house margaritas. Patio seating and family-sized portions.",
        "address": "Brentwood Blvd, Brentwood, CA 94513",
        "phone": "(925) 240-9013",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Sushi & Ramen",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Fresh sushi rolls, ramen bowls, and Japanese appetizers in Brentwood. Happy hour Monday through Friday 3–6 PM with half-price rolls.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9014",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Farmstead Café Brentwood",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Farm-to-table breakfast and lunch café in Brentwood. Locally sourced eggs, produce, and bread. Known for seasonal grain bowls and house-baked pastries.",
        "address": "Sand Creek Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9015",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Peacock Indian Restaurant",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Upscale Indian dining in Brentwood with regional specialties, clay oven breads, and a curated wine list. Reservations recommended on weekends.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9016",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Pizza Co.",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Hand-tossed pizzas, calzones, and pasta in Brentwood. Family dinner deals, online ordering, and fast delivery within 5 miles.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9017",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Urban Bites Brentwood",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Modern American café in Brentwood with gourmet sandwiches, grain bowls, and specialty coffee. Popular weekday lunch spot with fast service.",
        "address": "Lone Tree Way, Brentwood, CA 94513",
        "phone": "(925) 240-9018",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood BBQ Shack",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Slow-smoked ribs, brisket, and chicken in Brentwood. Homemade sides, sweet tea, and catering for backyard parties and community events.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9019",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Noodle Theory Brentwood",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Pan-Asian noodle bar in Brentwood with hand-pulled ramen, pad see ew, and pho. Build-your-own bowls with premium toppings and house-made broths.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9020",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunrise Breakfast Brentwood",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "All-day breakfast in Brentwood with skillets, eggs Benedict, French toast, and bottomless coffee. Outdoor patio open on weekends.",
        "address": "Brentwood Blvd, Brentwood, CA 94513",
        "phone": "(925) 240-9021",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Poke & Bowls",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Custom poke bowls with fresh ahi, salmon, shrimp, and tofu in Brentwood. Rice, salad, or mixed base with 20+ topping options.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9022",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Three Palms Cantina",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Coastal Mexican cuisine in Brentwood with fish tacos, ceviche, and house-infused margaritas. Rooftop patio open Thursday through Sunday.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9023",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Brentwood Burger Bar",
        "category": "Restaurants",
        "city": "Brentwood",
        "description": "Gourmet burgers, craft beer, and loaded fries in Brentwood. Smash patties, brioche buns, and weekly specials. Kid-friendly with a large patio.",
        "address": "Sand Creek Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9024",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Health & Wellness (10) —
    {
        "name": "Brentwood Family Practice",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Primary care for adults and children in Brentwood. Annual physicals, chronic care, and same-day sick appointments. Most insurance accepted.",
        "address": "Brentwood Blvd, Brentwood, CA 94513",
        "phone": "(925) 240-9025",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Pediatric Group",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Pediatrician group practice in Brentwood for newborns through teens. Well-child exams, vaccines, and behavioral health referrals.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9026",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Smile Dental",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Family dentistry in Brentwood with cleanings, whitening, Invisalign, implants, and children's dentistry. Evening appointments available.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9027",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Peak Performance Fitness",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Boutique gym in Brentwood with strength training, HIIT, yoga, and nutrition coaching. Personal training packages and drop-in classes available.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9028",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Physical Therapy",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Outpatient PT clinic in Brentwood for sports injuries, post-surgical recovery, and chronic pain. Dry needling, cupping, and manual therapy.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9029",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Mind & Wellness",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Therapy and counseling practice in Brentwood. Anxiety, couples therapy, trauma, and adolescent mental health. In-person and telehealth.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9030",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "East Bay Eye Associates",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Optometry clinic in Brentwood offering comprehensive eye exams, contact fittings, and designer eyewear. Same-day prescription fills available.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9031",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Chiropractic & Wellness",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Chiropractic adjustments, therapeutic massage, and nutrition counseling in Brentwood. New patient wellness exams include postural analysis.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9032",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Serenity Spa Brentwood",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Day spa in Brentwood with Swedish and deep tissue massage, facials, body wraps, and couples treatments. Gift certificates available year-round.",
        "address": "Sand Creek Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9033",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Urgent Care",
        "category": "Health & Wellness",
        "city": "Brentwood",
        "description": "Walk-in urgent care in Brentwood for illness, injuries, X-rays, and lab work. Open daily 8 AM–9 PM with short average wait times.",
        "address": "Lone Tree Way, Brentwood, CA 94513",
        "phone": "(925) 240-9034",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },

    # — Education (6) —
    {
        "name": "Brentwood Learning Academy",
        "category": "Education",
        "city": "Brentwood",
        "description": "After-school tutoring for K–12 in Brentwood. Math, reading, writing, and test prep with credentialed teachers in small groups.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9035",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Little Explorers Preschool Brentwood",
        "category": "Education",
        "city": "Brentwood",
        "description": "Licensed preschool in Brentwood for ages 2–5. Play-based learning, bilingual staff, STEM activities, and extended care for working families.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9036",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Music School",
        "category": "Education",
        "city": "Brentwood",
        "description": "Piano, guitar, voice, and violin lessons for all ages in Brentwood. Group and private instruction, recitals, and summer music camps.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9037",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Swim & Water Safety",
        "category": "Education",
        "city": "Brentwood",
        "description": "Swim lessons and water safety instruction for infants through teens in Brentwood. Heated outdoor pool and year-round indoor instruction.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9038",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Gymnastics Center",
        "category": "Education",
        "city": "Brentwood",
        "description": "Gymnastics and tumbling classes for toddlers through teens in Brentwood. Recreational and competitive teams, birthday party packages available.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9039",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tri Delta Martial Arts Brentwood",
        "category": "Education",
        "city": "Brentwood",
        "description": "Karate and jiu-jitsu classes for kids and adults in Brentwood. Character development program, belt system, and anti-bullying curriculum.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9040",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Pet Services (5) —
    {
        "name": "Brentwood Vet Clinic",
        "category": "Pet Services",
        "city": "Brentwood",
        "description": "Veterinary clinic in Brentwood for dogs and cats. Wellness exams, vaccinations, dental cleanings, spay/neuter, and senior pet care.",
        "address": "Brentwood Blvd, Brentwood, CA 94513",
        "phone": "(925) 240-9041",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Dog Spa & Grooming",
        "category": "Pet Services",
        "city": "Brentwood",
        "description": "Premium dog grooming in Brentwood. Full grooms, bath packages, de-shed treatments, and puppy's first groom experience. Book online.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9042",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Happy Paws Boarding Brentwood",
        "category": "Pet Services",
        "city": "Brentwood",
        "description": "Dog boarding and daycare in Brentwood with climate-controlled suites, outdoor play yards, and daily photo updates. Cage-free environment.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9043",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Mobile Pet Vet",
        "category": "Pet Services",
        "city": "Brentwood",
        "description": "Mobile veterinary service in Brentwood. Wellness exams, vaccines, blood draws, and minor treatments at your home. By appointment.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9044",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Dog Training Studio",
        "category": "Pet Services",
        "city": "Brentwood",
        "description": "Positive reinforcement dog training in Brentwood. Puppy socialization, basic obedience, reactive dog classes, and private consultations.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9045",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Beauty & Spa (3) —
    {
        "name": "Brentwood Beauty Bar",
        "category": "Beauty & Spa",
        "city": "Brentwood",
        "description": "Lash extensions, brow lamination, and waxing studio in Brentwood. Volume and classic lash sets, express services, and walk-in brow shaping.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9046",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Luxe Hair Studio Brentwood",
        "category": "Beauty & Spa",
        "city": "Brentwood",
        "description": "Upscale hair salon in Brentwood specializing in balayage, color corrections, extensions, and bridal styling. Book online for priority appointments.",
        "address": "Sand Creek Rd, Brentwood, CA 94513",
        "phone": "(925) 240-9047",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Polish & Pedicure Brentwood",
        "category": "Beauty & Spa",
        "city": "Brentwood",
        "description": "Nail salon in Brentwood offering gel manicures, acrylic sets, spa pedicures, and paraffin treatments. Clean tools and relaxing atmosphere.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9048",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Automotive (2) —
    {
        "name": "Brentwood Auto Service Center",
        "category": "Automotive",
        "city": "Brentwood",
        "description": "Full-service auto repair in Brentwood for all makes and models. Oil changes, brakes, tires, alignment, smog, and transmission service.",
        "address": "Brentwood Blvd, Brentwood, CA 94513",
        "phone": "(925) 240-9049",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Brentwood Car Detailing Co.",
        "category": "Automotive",
        "city": "Brentwood",
        "description": "Auto detailing in Brentwood with hand wash, interior steam clean, paint correction, and ceramic coating. Mobile detailing available on request.",
        "address": "Brentwood, CA 94513",
        "phone": "(925) 240-9050",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
]


def insert_businesses():
    url = f"{SUPABASE_URL}/rest/v1/businesses"
    headers = {
        "apikey": SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }
    payload = json.dumps(BUSINESSES).encode("utf-8")
    req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            print(f"✅  Inserted {len(result)} businesses successfully!")
            by_city = {}
            for biz in result:
                city = biz.get("city", "Unknown")
                by_city[city] = by_city.get(city, 0) + 1
            for city, count in sorted(by_city.items()):
                print(f"   {city}: {count} businesses")
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"❌  HTTP {e.code}: {body}")
        raise


if __name__ == "__main__":
    print("🌱  MoHoLocal — Seeding batch 6 (150 businesses: Lathrop + Manteca + Brentwood)...")
    print(f"   Lathrop: 50 | Manteca: 50 | Brentwood: 50")
    insert_businesses()
