#!/usr/bin/env python3
"""
MoHoLocal — Seed 100 additional businesses: Mountain House + Tracy
Focus: Home Services, Restaurants, Health & Wellness, Education, Family Services
Run from Mac terminal: python3 ~/Desktop/MoHoLocal/seed_businesses_5.py
"""

import json
import urllib.request
import urllib.error

SUPABASE_URL = "https://ozjlfgipfzykzrjakwzb.supabase.co"
SERVICE_ROLE_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
    ".eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96amxmZ2lwZnp5a3pyamFrd3piIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjQzMzI3NiwiZXhwIjoyMDg4MDA5Mjc2fQ"
    ".g9f2Il1nWEfgyuvTXHUiHn4EgWsrHVV1QBbdxehT0gM"
)

BUSINESSES = [

    # ═══════════════════════════════════════════════════════════════════════
    # MOUNTAIN HOUSE  (50)
    # ═══════════════════════════════════════════════════════════════════════

    # — Home Services (12) —
    {
        "name": "Mountain House Roofing Co.",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Licensed roofers serving Mountain House with new installs, repairs, and storm damage inspections. Free estimates, same-week service.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9001",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "209 HVAC Solutions",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Heating, cooling, and ventilation specialists for Mountain House homes. AC tune-ups, new system installs, and emergency repair available 7 days a week.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9002",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Valley Fence & Gates",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Custom wood, vinyl, and wrought iron fencing for Mountain House properties. Automatic gate installation and repair. Licensed and insured.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9003",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunrise Tile & Flooring",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Tile, hardwood, and LVP flooring installation for Mountain House homes. Kitchen and bathroom tile work, grout restoration, and stair refinishing.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9004",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mountain House Pool Service",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Weekly pool cleaning, chemical balancing, equipment repair, and seasonal open/close service for Mountain House residents.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9005",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Premier Pest Control — Mountain House",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Family-safe pest control for ants, spiders, rodents, and gophers in Mountain House. Monthly and quarterly treatment plans available.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9006",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Wicklund Concrete & Pavers",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Concrete driveways, stamped patios, and paver installations for Mountain House homes. Free design consultations and competitive quotes.",
        "address": "Wicklund Ave, Mountain House, CA 95391",
        "phone": "(209) 456-9007",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mustang Garage Doors",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Garage door installation, spring repair, and smart opener upgrades for Mountain House residences. Same-day emergency service.",
        "address": "Mustang Pkwy, Mountain House, CA 95391",
        "phone": "(209) 456-9008",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Clean Air Duct Pros",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "HVAC duct cleaning, dryer vent cleaning, and air quality inspections for Mountain House families. NADCA-certified technicians.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9009",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Traditions Painting & Drywall",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Interior and exterior painting, drywall repair, and texture matching for Mountain House homes. Clean work, on-time finish.",
        "address": "Traditions St, Mountain House, CA 95391",
        "phone": "(209) 456-9010",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "MH Gutter & Downspout Co.",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Seamless gutter installation, cleaning, and leaf guard systems for Mountain House properties. Free inspection with every service call.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9011",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Rosewood Remodeling",
        "category": "Home Services",
        "city": "Mountain House",
        "description": "Full kitchen and bathroom remodeling for Mountain House homeowners. Design-build service from concept to finish with licensed general contractors.",
        "address": "Rosewood Way, Mountain House, CA 95391",
        "phone": "(209) 456-9012",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Restaurants (12) —
    {
        "name": "Biryani House Mountain House",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Authentic dum biryani, karahi, and naan bread baked fresh daily. Popular with Mountain House's South Asian community. Dine-in and takeout.",
        "address": "19700 Mountain House Pkwy, Mountain House, CA 95391",
        "phone": "(209) 456-9013",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pho & More — Mountain House",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Vietnamese pho, banh mi, spring rolls, and boba tea. Family-run and community-loved in Mountain House. Fast service for lunch crowds.",
        "address": "Mountain House Pkwy, Mountain House, CA 95391",
        "phone": "(209) 456-9014",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Halal Guys Grill MH",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Halal burgers, shawarma wraps, and loaded fries in Mountain House. All meats hand-cut and certified halal. Open late on weekends.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9015",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Bombay Bites",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Casual Indian street food — chaat, samosas, pav bhaji, and masala chai. Perfect for quick lunches and after-school snacks in Mountain House.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9016",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Breakfast Nook MH",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "All-day breakfast café serving pancakes, egg benedicts, avocado toast, and specialty coffee in Mountain House. Opens at 6 AM daily.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9017",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pizza Central Mountain House",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Hand-tossed pizzas, calzones, and pasta baked fresh in Mountain House. Family meal deals and fast delivery within the community.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9018",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sushi Sakura MH",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Fresh sushi rolls, sashimi, ramen, and Japanese appetizers. Mountain House's neighborhood Japanese restaurant with happy hour daily 4–6 PM.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9019",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Taqueria El Rancho MH",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Authentic Mexican tacos, burritos, and tortas made with homemade salsas. Carne asada and al pastor are house favorites in Mountain House.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9020",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Mango Tree Café",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Filipino-inspired café serving pancit, lumpia, halo-halo, and pandesal. A community favorite for weekend brunch in Mountain House.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9021",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Goldfields Burger Bar",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Smash burgers, crispy chicken sandwiches, and thick shakes in Mountain House. Build your own burger with locally sourced toppings.",
        "address": "W Grant Line Rd, Mountain House, CA 95391",
        "phone": "(209) 456-9022",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Chai & Chaat Corner",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "South Asian street snacks, desi chai, and fresh lassi. Popular after-school and weekend spot in Mountain House. Vegetarian-friendly menu.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9023",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "SubStation MH",
        "category": "Restaurants",
        "city": "Mountain House",
        "description": "Build-your-own subs with freshly baked bread, premium meats, and local veggies. Quick lunch destination in Mountain House with online ordering.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9024",
        "website": None,
        "rating": 4.3,
        "status": "approved",
        "verified": True,
    },

    # — Health & Wellness (10) —
    {
        "name": "Mountain House Family Medicine",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Primary care for all ages in Mountain House. Annual physicals, sick visits, chronic disease management, and telehealth appointments available.",
        "address": "19720 Mountain House Pkwy, Mountain House, CA 95391",
        "phone": "(209) 456-9025",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunrise Pediatrics MH",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Board-certified pediatrician serving newborns through teens in Mountain House. Well-child exams, immunizations, and same-day sick appointments.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9026",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "CoreFit Studio Mountain House",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Boutique fitness studio offering HIIT, yoga, and strength classes in Mountain House. Childwatch available during morning sessions.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9027",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mountain House Dental Care",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "General and cosmetic dentistry for families in Mountain House. Cleanings, fillings, Invisalign, and pediatric dentistry. Most insurance accepted.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9028",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tranquil Mind Therapy",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Licensed therapists offering individual, couples, and family counseling in Mountain House. Telehealth and in-person sessions available.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9029",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Valley Eye Center MH",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Optometry clinic in Mountain House offering eye exams, contact lens fittings, and a large selection of frames for adults and children.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9030",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mountain House Chiropractic",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Chiropractic adjustments, spinal decompression, and sports injury rehab for Mountain House residents. Walk-ins welcome on Tuesdays and Thursdays.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9031",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Bloom Women's Health",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "OB-GYN and women's wellness clinic in Mountain House. Prenatal care, annual exams, family planning, and menopause management.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9032",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "MH Urgent Care Center",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Walk-in urgent care in Mountain House for minor injuries, illness, lab work, and X-rays. Open 7 days, no appointment needed.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9033",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Lotus Spa & Wellness",
        "category": "Health & Wellness",
        "city": "Mountain House",
        "description": "Day spa offering deep tissue massage, facials, prenatal massage, and reflexology in Mountain House. Gift cards available year-round.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9034",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Education (6) —
    {
        "name": "Bright Futures Learning Center",
        "category": "Education",
        "city": "Mountain House",
        "description": "After-school tutoring and enrichment for K–8 students in Mountain House. Math, reading, science, and test prep with certified teachers.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9035",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mountain House Music Academy",
        "category": "Education",
        "city": "Mountain House",
        "description": "Piano, guitar, violin, and vocal lessons for kids and adults in Mountain House. In-home and studio sessions available year-round.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9036",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Little Scholars Preschool",
        "category": "Education",
        "city": "Mountain House",
        "description": "Licensed preschool for ages 2–5 in Mountain House with play-based curriculum, bilingual instruction, and extended care options.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9037",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Code Kids MH",
        "category": "Education",
        "city": "Mountain House",
        "description": "Coding and robotics classes for children ages 6–14 in Mountain House. Scratch, Python, and LEGO robotics taught in small group sessions.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9038",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "MH SAT & College Prep",
        "category": "Education",
        "city": "Mountain House",
        "description": "SAT, ACT, and AP exam prep for high school students in Mountain House. One-on-one tutoring and small group weekend classes.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9039",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Dance Fusion Academy MH",
        "category": "Education",
        "city": "Mountain House",
        "description": "Ballet, hip-hop, Bollywood, and contemporary dance classes for children and teens in Mountain House. Annual recitals and competition team.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9040",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },

    # — Pet Services (5) —
    {
        "name": "Mountain House Veterinary Clinic",
        "category": "Pet Services",
        "city": "Mountain House",
        "description": "Full-service vet clinic in Mountain House for dogs, cats, and small animals. Wellness exams, dental cleanings, surgery, and urgent care.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9041",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Happy Tails Pet Boarding",
        "category": "Pet Services",
        "city": "Mountain House",
        "description": "Overnight pet boarding and daycare for dogs and cats in Mountain House. Climate-controlled suites, daily exercise, and webcam check-ins.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9042",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "MH Mobile Vet",
        "category": "Pet Services",
        "city": "Mountain House",
        "description": "Mobile veterinary service bringing wellness exams, vaccines, and minor treatments to your Mountain House doorstep. By appointment.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9043",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Snip & Wag Grooming",
        "category": "Pet Services",
        "city": "Mountain House",
        "description": "Dog grooming studio in Mountain House specializing in breed cuts, deshedding treatments, and spa baths. Book online or walk in.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9044",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Mountain House Dog Park Trainer",
        "category": "Pet Services",
        "city": "Mountain House",
        "description": "On-leash and off-leash obedience training for dogs in Mountain House. Puppy socialization, reactive dog rehabilitation, and agility courses.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9045",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Beauty & Spa (3) —
    {
        "name": "Glow Beauty Bar MH",
        "category": "Beauty & Spa",
        "city": "Mountain House",
        "description": "Eyelash extensions, brow lamination, and tinting studio in Mountain House. Walk-ins welcome for express services. Online booking available.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9046",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Shear Perfection Salon MH",
        "category": "Beauty & Spa",
        "city": "Mountain House",
        "description": "Full-service hair salon in Mountain House for cuts, color, highlights, keratin treatments, and bridal styling. Family-friendly atmosphere.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9047",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "NailPro Mountain House",
        "category": "Beauty & Spa",
        "city": "Mountain House",
        "description": "Nail salon offering gel manicures, acrylic sets, pedicures, and nail art in Mountain House. Clean tools, relaxing atmosphere, and fast service.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9048",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Automotive (2) —
    {
        "name": "Mountain House Auto Repair",
        "category": "Automotive",
        "city": "Mountain House",
        "description": "Honest auto repair in Mountain House for all makes and models. Oil changes, brake service, transmission, and smog checks. Free diagnostics.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9049",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "EV Charge & Go MH",
        "category": "Automotive",
        "city": "Mountain House",
        "description": "Electric vehicle service center in Mountain House. Level 2 and DC fast charging, EV battery diagnostics, and Tesla-compatible repair.",
        "address": "Mountain House, CA 95391",
        "phone": "(209) 456-9050",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # ═══════════════════════════════════════════════════════════════════════
    # TRACY  (50)
    # ═══════════════════════════════════════════════════════════════════════

    # — Home Services (12) —
    {
        "name": "Tracy Plumbing Pros",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Licensed plumbers in Tracy for water heater installs, drain cleaning, slab leaks, and whole-home repiping. 24/7 emergency line.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9001",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Central Valley Roofing — Tracy",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Residential roofing installation and repair in Tracy. Tile, shingle, and flat roof specialists. Storm damage assessments and insurance claims assistance.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9002",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Solar & Battery",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Solar panel installation and whole-home battery backup for Tracy homeowners. NEM 3.0 experts with 25-year workmanship warranty.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9003",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Naglee Landscaping & Irrigation",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Full-service landscaping, irrigation design, and drought-tolerant garden installations for Tracy homes and commercial properties.",
        "address": "Naglee Rd, Tracy, CA 95376",
        "phone": "(209) 835-9004",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Pool & Spa Specialists",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Pool cleaning, repair, equipment replacement, and new pool construction in Tracy and surrounding areas. Weekly service plans starting at $120/month.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9005",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Schulte Electric",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Licensed electricians in Tracy for panel upgrades, EV charger installs, outlet additions, and whole-home rewiring. Free estimates.",
        "address": "Schulte Rd, Tracy, CA 95376",
        "phone": "(209) 835-9006",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Flooring & Carpet",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Hardwood, LVP, carpet, and tile installation for Tracy homes. In-home samples, free measurements, and competitive pricing.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9007",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "MacArthur Painting Co.",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Interior and exterior residential painting in Tracy. Clean, professional crews and premium paints. Color consultation included.",
        "address": "MacArthur Dr, Tracy, CA 95376",
        "phone": "(209) 835-9008",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Fence & Deck Co.",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Wood, vinyl, and aluminum fencing plus deck construction and refinishing in Tracy. Licensed and insured with 10-year workmanship guarantee.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9009",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Fresh Start Maid Service — Tracy",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Recurring and one-time residential cleaning in Tracy. Move-out deep cleans, post-construction cleanup, and eco-friendly product options.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9010",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy HVAC & Air Quality",
        "category": "Home Services",
        "city": "Tracy",
        "description": "Heating and cooling repair, new system installation, and air quality testing for Tracy homes. Financing available on all new systems.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9011",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Holly Dr Handyman",
        "category": "Home Services",
        "city": "Tracy",
        "description": "General handyman services for Tracy homeowners. Drywall, minor plumbing, door hardware, tile repair, and furniture assembly.",
        "address": "Holly Dr, Tracy, CA 95376",
        "phone": "(209) 835-9012",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },

    # — Restaurants (12) —
    {
        "name": "El Jardin Mexican Grill",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Family-owned Mexican restaurant in Tracy serving enchiladas, carnitas, and handmade tortillas since 2005. Margarita happy hour weekdays 3–6 PM.",
        "address": "W 11th St, Tracy, CA 95376",
        "phone": "(209) 835-9013",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Golden Chopsticks Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Chinese-American favorites including orange chicken, kung pao, fried rice, and dim sum on weekends. Catering available for Tracy events.",
        "address": "Tracy Blvd, Tracy, CA 95376",
        "phone": "(209) 835-9014",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Tandoor Kitchen",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "North Indian cuisine with clay oven breads, butter chicken, lamb rogan josh, and vegetarian thalis. Lunch buffet Monday–Friday.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9015",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Coastal Fish & Chips Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Classic beer-battered fish and chips, chowder, calamari, and grilled seafood plates. Tracy's neighborhood seafood spot with outdoor patio.",
        "address": "Central Ave, Tracy, CA 95376",
        "phone": "(209) 835-9016",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Sunrise Dim Sum & Tea",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Traditional Cantonese dim sum served cart-style on weekends and à la carte daily. Known for har gow, char siu bao, and egg tarts in Tracy.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9017",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Habit Burgers — Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Charburgers, Santa Barbara-style sandwiches, salads, and milkshakes at Tracy's popular fast-casual burger spot on Tracy Blvd.",
        "address": "Tracy Blvd, Tracy, CA 95376",
        "phone": "(209) 835-9018",
        "website": None,
        "rating": 4.4,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Ramen Republic Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Tonkotsu, shoyu, and spicy miso ramen with homemade noodles in Tracy. Build-your-own bowl with premium toppings. Open for lunch and dinner.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9019",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Taqueria La Paloma Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Street tacos, tamales, and pozole made fresh daily in Tracy. Open early for breakfast burritos and late for weekend crowds.",
        "address": "W 11th St, Tracy, CA 95376",
        "phone": "(209) 835-9020",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Farmhouse Kitchen Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Farm-to-table café in Tracy with seasonal salads, grain bowls, and locally sourced sandwiches. Specialty coffee and organic smoothies.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9021",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Bella Italia Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Authentic Italian trattoria in Tracy with wood-fired pizza, handmade pasta, and a curated Italian wine list. Reservations recommended on weekends.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9022",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Smokey's Wings & Things",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Crispy chicken wings in 20 sauces, loaded fries, and mac bites. Popular sports bar menu with game-day specials in Tracy.",
        "address": "Corral Hollow Rd, Tracy, CA 95376",
        "phone": "(209) 835-9023",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Pho Saigon Tracy",
        "category": "Restaurants",
        "city": "Tracy",
        "description": "Traditional Vietnamese pho, bun bo hue, banh xeo, and fresh spring rolls. Tracy's go-to Vietnamese restaurant with generous portions.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9024",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Health & Wellness (10) —
    {
        "name": "Tracy Family Health Center",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Primary care clinic in Tracy accepting new patients. Physicals, chronic care management, immunizations, and same-day sick visits.",
        "address": "Tracy Blvd, Tracy, CA 95376",
        "phone": "(209) 835-9025",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Pediatrics & Urgent Care",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Pediatric wellness and urgent care under one roof in Tracy. Sick visits, sports physicals, vaccines, and after-hours appointments.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9026",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Iron Peak Fitness Tracy",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "24-hour gym in Tracy with free weights, cardio machines, group fitness classes, and personal training. No contracts required.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9027",
        "website": None,
        "rating": 4.5,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Spine & Rehab",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Physical therapy and chiropractic care for back pain, sports injuries, and post-surgical rehab in Tracy. Most insurance plans accepted.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9028",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Bright Smiles Dental Tracy",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "General and cosmetic dentistry for Tracy families. Invisalign, teeth whitening, implants, and pediatric dental care. Evening hours available.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9029",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Mental Health & Counseling",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Licensed therapists in Tracy specializing in anxiety, depression, trauma, and family counseling. Sliding scale fees and telehealth available.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9030",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Women's Wellness Clinic",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "OB-GYN, prenatal care, and women's health services in Tracy. Accepting new patients with most major insurance plans.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9031",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Central Valley Eye Care",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Optometry and eye health clinic in Tracy. Comprehensive exams, contact fittings, and a wide selection of designer frames and lenses.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9032",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Balance Yoga & Pilates Tracy",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Yoga and pilates studio in Tracy with beginner through advanced classes. Aerial yoga, restorative, and prenatal offerings. Class packs available.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9033",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Revive Medical Spa Tracy",
        "category": "Health & Wellness",
        "city": "Tracy",
        "description": "Medical spa in Tracy offering Botox, fillers, laser hair removal, and HydraFacials. Board-certified providers and private treatment suites.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9034",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },

    # — Education (6) —
    {
        "name": "Tracy Learning Hub",
        "category": "Education",
        "city": "Tracy",
        "description": "After-school tutoring center in Tracy for K–12 students. Math, English, science, and homework help with experienced credentialed teachers.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9035",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Martial Arts Academy",
        "category": "Education",
        "city": "Tracy",
        "description": "Karate, taekwondo, and jiu-jitsu for children and adults in Tracy. Character development curriculum, belt promotion system, and after-school program.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9036",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Stepping Stones Daycare Tracy",
        "category": "Education",
        "city": "Tracy",
        "description": "Licensed daycare and preschool for infants through kindergarten in Tracy. CACFP-approved meals, structured learning, and flexible full/part-day schedules.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9037",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy School of Arts",
        "category": "Education",
        "city": "Tracy",
        "description": "Visual arts, pottery, and watercolor classes for kids and adults in Tracy. Summer camps, birthday workshops, and private lessons available.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9038",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Kumon Math & Reading — Tracy",
        "category": "Education",
        "city": "Tracy",
        "description": "Kumon study center in Tracy offering self-paced math and reading programs for students from preschool through high school level.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9039",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Language School",
        "category": "Education",
        "city": "Tracy",
        "description": "Spanish, Mandarin, and Hindi language classes for children and adults in Tracy. Private tutoring, group classes, and immersion weekend programs.",
        "address": "Tracy, CA 95377",
        "phone": "(209) 835-9040",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },

    # — Pet Services (5) —
    {
        "name": "Tracy Animal Hospital",
        "category": "Pet Services",
        "city": "Tracy",
        "description": "Full-service animal hospital in Tracy providing wellness care, emergency services, surgery, and dental cleanings for dogs, cats, and exotic pets.",
        "address": "Tracy Blvd, Tracy, CA 95376",
        "phone": "(209) 835-9041",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "The Wagging Tail — Tracy",
        "category": "Pet Services",
        "city": "Tracy",
        "description": "Dog daycare, overnight boarding, and group play in Tracy. Cage-free environment, daily activity reports, and webcam access for pet parents.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9042",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy Mobile Pet Grooming",
        "category": "Pet Services",
        "city": "Tracy",
        "description": "Mobile grooming van serving Tracy with full groom packages, bath and brush, and specialty breed cuts. Book online for at-home service.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9043",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Paws & Play Pet Supply Tracy",
        "category": "Pet Services",
        "city": "Tracy",
        "description": "Independent pet supply store in Tracy stocking premium food, toys, supplements, and accessories for dogs, cats, birds, and small animals.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9044",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy K9 Training Center",
        "category": "Pet Services",
        "city": "Tracy",
        "description": "Professional dog training in Tracy using positive reinforcement. Puppy classes, basic obedience, off-leash reliability, and protection sport intro.",
        "address": "Corral Hollow Rd, Tracy, CA 95376",
        "phone": "(209) 835-9045",
        "website": None,
        "rating": 4.9,
        "status": "approved",
        "verified": True,
    },

    # — Beauty & Spa (3) —
    {
        "name": "Luxe Lash & Brow Tracy",
        "category": "Beauty & Spa",
        "city": "Tracy",
        "description": "Lash extensions, brow microblading, and tinting studio in Tracy. Russian volume, classic sets, and express lash fills available.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9046",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Radiance Skin Studio Tracy",
        "category": "Beauty & Spa",
        "city": "Tracy",
        "description": "Facial treatments, chemical peels, microdermabrasion, and acne therapy by licensed estheticians in Tracy. First facial consultation is free.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9047",
        "website": None,
        "rating": 4.7,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Studio 11 Hair Salon Tracy",
        "category": "Beauty & Spa",
        "city": "Tracy",
        "description": "Full-service hair salon on 11th St in Tracy. Cuts, balayage, keratin smoothing, and extensions. Walk-ins welcome on Tuesdays.",
        "address": "W 11th St, Tracy, CA 95376",
        "phone": "(209) 835-9048",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },

    # — Automotive (2) —
    {
        "name": "Tracy Tire & Auto Center",
        "category": "Automotive",
        "city": "Tracy",
        "description": "Tire sales, rotation, alignment, oil changes, and brake service for all vehicles in Tracy. Same-day appointments and fleet service available.",
        "address": "MacArthur Dr, Tracy, CA 95376",
        "phone": "(209) 835-9049",
        "website": None,
        "rating": 4.6,
        "status": "approved",
        "verified": True,
    },
    {
        "name": "Tracy European Auto Repair",
        "category": "Automotive",
        "city": "Tracy",
        "description": "Specialist auto repair shop in Tracy for BMW, Mercedes, Audi, and Volkswagen. Factory-level diagnostics at independent shop pricing.",
        "address": "Tracy, CA 95376",
        "phone": "(209) 835-9050",
        "website": None,
        "rating": 4.8,
        "status": "approved",
        "verified": True,
    },
]


def insert_businesses():
    url = f"{SUPABASE_URL}/rest/v1/businesses"
    headers = {
        "apikey": SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation",
    }
    payload = json.dumps(BUSINESSES).encode("utf-8")
    req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            print(f"✅  Inserted {len(result)} businesses successfully!")
            by_city = {}
            for biz in result:
                city = biz.get("city", "Unknown")
                by_city[city] = by_city.get(city, 0) + 1
            for city, count in sorted(by_city.items()):
                print(f"   {city}: {count} businesses")
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"❌  HTTP {e.code}: {body}")
        raise


if __name__ == "__main__":
    print("🌱  MoHoLocal — Seeding batch 5 (100 businesses: Mountain House + Tracy)...")
    print(f"   Mountain House: 50 | Tracy: 50")
    insert_businesses()
